### ISSUE TITLE
蓝牙突然不可用了

### ISSUE THREAD

**Issue by 13371027447** [MotorBottle/Hackintosh-High-Sierra-10600KF-GTX1070-MSI-Z490i-Unify#3]
本来一开始好好的 突然不可用了 设置里直接没有蓝牙图标了 🥶🥶🥶

**Comment by MotorBottle** [comment]
hackintool看看驱动启用了没

**Comment by 13371027447** [comment]
我这一断电重启又好了…什么情况

**Comment by 13371027447** [comment]
断电重启又好了

**Comment by 13371027447** [comment]
….

**Comment by 13371027447** [comment]
感谢老哥提供的efi！ 您说的关sip怎么操作呢 我在网上没有找到对应合适的教程  请问您方便告知下嘛

**Comment by MotorBottle** [comment]
参考dortania的手册https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip

可以在启动项下方添加csr_active_config项，值为FF030000（10.13）
